apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - deployment.yaml

# NOTE: Removed commonLabels because it modifies spec.selector which is immutable
# Labels are already defined in the deployment.yaml itself
